"""initial tables

Revision ID: 0ebc29cfbd5a
Revises: 
Create Date: 2026-07-06 13:00:44.225382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebc29cfbd5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_bookings_mentor_id'), 'bookings', ['mentor_id'], unique=False)
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.add_column('forum_posts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_posts', 'created_at')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_column('comments', 'created_at')
    op.drop_index(op.f('ix_bookings_mentor_id'), table_name='bookings')
    op.drop_column('bookings', 'created_at')
    # ### end Alembic commands ###
